### ISSUE TITLE
Getting Strings max length 1

### ISSUE THREAD

**Issue by JasperGeurtz** [JavaBWAPI/JBWAPI#18]
Fix autogenerated

`Buffers.toString(sharedMemory, offset, 1);`

where 1 should be a bigger value

**Comment by JasperGeurtz** [comment]
https://github.com/JavaBWAPI/JBWAPI/commit/a1c6b1b692e6b6066ff03038d26dacb1e84081fb

**Comment by Bytekeeper** [comment]
Fixed with a1c6b1b692e6b6066ff03038d26dacb1e84081fb
