### ISSUE TITLE
PurpleWave works but gateways are not being build

### ISSUE THREAD

**Issue by JasperGeurtz** [JavaBWAPI/JBWAPI#22]
investigate

https://github.com/JasperGeurtz/PurpleWave/commit/22c2333fc241655b3f9b002360f9cfbe6fc6ae07

**Comment by JasperGeurtz** [comment]
Pylons get build though, so probably a bug related to Psi

**Comment by dgant** [comment]
PW doesn't actually check Psi (ie Game.getPower) through the API -- it calculates the psi grid on its own. 

You could double-check against the JBWAPI branch of the mainline PW repo: https://github.com/dgant/PurpleWave/tree/jbwapi

**Comment by dgant** [comment]
(on further inspection, it looks like you're already using the JBWAPI branch :D)

**Comment by JasperGeurtz** [comment]
I think (J)BWAPI also internally checks Psi if a build command is issued for a protoss building

The issue was for the "Buildings don't reliably construct" in https://github.com/dgant/PurpleWave/commit/16613bfcb7b9685155966dd55d7d33c2ae6b2237 

I'll do more research this weekend

**Comment by JasperGeurtz** [comment]
Should be fixed with https://github.com/JavaBWAPI/JBWAPI/commit/8a8485fd4127419042a2a02a325f03bb99789cd9
