### ISSUE TITLE
getBuildTile doesn't seem to work

### ISSUE THREAD

**Issue by impie66** [JavaBWAPI/JBWAPI#29]
getBuildLocation seems to be returning the same location with different start points.

This is what i did
```
while(test.size() <= 4){
TilePosition build = game.getBuildLocation(UnitType.Terran_Barracks, self.getStartLocation(), 300);
   if(build != null){
	  test.add(build);
	  System.out.println(build);
	  game.pingMinimap(build.toPosition());
  }
}
```

I ran this multiple times on the same map with different start positions 
What returned was [1000, 1001]

**Comment by N00byEdge** [comment]
That just so happens to be `const TilePosition None{32000 / TILEPOSITION_SCALE, 32032 / TILEPOSITION_SCALE};`

**Comment by JasperGeurtz** [comment]
Thanks for finding this, should be fixed with https://github.com/JavaBWAPI/JBWAPI/commit/7d8e52cec32b3b413cbd8b00f296dac136f54089 (very dumb mistake...)

At least I now got:
[37, 9]
[37, 9]
[37, 9]
[37, 9]
