### ISSUE TITLE
ArrayIndexOutOfBoundsException for TechType.Nuclear_Strike.energyCost();

### ISSUE THREAD

**Issue by impie66** [JavaBWAPI/JBWAPI#38]
Nuke doesn't have an value for energyCost

[Reference](https://github.com/JavaBWAPI/JBWAPI/blob/develop/src/main/java/bwapi/TechType.java#L56)
35 values, 36 TechTypes?

Just needs another value for nuke

_c++ sucks leemayo_

**Comment by JasperGeurtz** [comment]
Fixed in https://github.com/JavaBWAPI/JBWAPI/commit/f4404ff34509de1c9c68a27d5613326f9ca3bb3d
