### ISSUE TITLE
isGatheringMinerals issue with LatCom on

### ISSUE THREAD

**Issue by Gathers** [JavaBWAPI/JBWAPI#48]
Hi, after converting MadMix from BWMirror to JBWAPI I noticed it didn't mine the same way. Looking deeper it seems isGatheringMinerals is returning false for a single frame, 2 frames after the order to gather.

Running a modified version of the LatencyListener test shows the order changing from MoveToMinerals to Harvest1 in frame 2. Running the same test in BWMirror (with older BWAPI) shows the order MoveToMinerals in frame 2.

> latcom: true
latcom frames: 2
mineralsAmout: 50
FRAME: 0
Worker 0
Unit::isGathering: game.isLatComEnabled()=true self().isGathering.valid(0)=true self().isGathering.get()=true unitData.isGathering()=false
gatheringMinerals: true
order: MoveToMinerals
orderTargetId: null
FRAME: 1
Worker 0
Unit::isGathering: game.isLatComEnabled()=true self().isGathering.valid(1)=false self().isGathering.get()=true unitData.isGathering()=true
gatheringMinerals: true
order: MoveToMinerals
orderTargetId: null
FRAME: 2
Worker 0
Unit::isGathering: game.isLatComEnabled()=true self().isGathering.valid(2)=false self().isGathering.get()=true unitData.isGathering()=false
gatheringMinerals: false
order: Harvest1
orderTargetId: bwapi.Unit@b4
orderTargetType: Resource_Mineral_Field
FRAME: 3
Worker 0
Unit::isGathering: game.isLatComEnabled()=true self().isGathering.valid(3)=false self().isGathering.get()=true unitData.isGathering()=true
gatheringMinerals: true
order: MoveToMinerals
orderTargetId: bwapi.Unit@b4
orderTargetType: Resource_Mineral_Field

From what I can tell this happens with all races and on both 1.0 and develop.

**Comment by Bytekeeper** [comment]
Well, it seems as if `isGatheringGas/Minerals` are incomplete:
https://github.com/bwapi/bwapi/blob/3438abd8e0222f37934ba62b2130c3933b067678/bwapi/Shared/UnitShared.cpp#L449
We need to port that, and it's not really latcom related I think (but has a bigger impact there of course).

**Comment by Bytekeeper** [comment]
At first glance, looks correct.

**Comment by JasperGeurtz** [comment]
```unitData.isGathering();``` returns `false` on frame 2, so I believe that something is going wrong serverside, not clientside

**Comment by N00byEdge** [comment]
To be fair, we could just add another frame of resource gathering to the beginning. IIRC, the worker goes non-idle at the right point, but it definitely could be that the resource gathering flag is updated a frame later. Which would suck.

**Comment by JasperGeurtz** [comment]
Fixed in https://github.com/bwapi/bwapi/pull/845 , will be updated in this repo once a new BWAPI version is released
