### ISSUE TITLE
Unique identifier for units

### ISSUE THREAD

**Issue by JuanPabloMF** [JavaBWAPI/JBWAPI#59]
I have been trying to look for a unique identifier of the units of the game. 
The following code gives me for the 4 initial SCVs an ID of 0 (wether it be replayID or ID)

```
import bwapi.BWClient;
import bwapi.DefaultBWListener;
import bwapi.Flag;
import bwapi.Game;
import bwapi.Player;
import bwapi.Unit;

public class Bot extends DefaultBWListener {
    BWClient bwClient;
    Game game;

    @Override
    public void onStart() {
        game = bwClient.getGame();
        game.enableFlag(Flag.UserInput);
        game.enableFlag(Flag.CompleteMapInformation);
        Player self = game.self();
    }

    @Override
    public void onFrame() {
        String text = "Unit ID: ";
        for(Unit unit : game.getSelectedUnits()) {
        	text = text + unit.getID() + ',';
        }
        text = text.substring(0, text.length() - 1);
        game.drawTextScreen(200,100, text);
        
        String text2 = "Unit Replay ID: ";
        for(Unit unit : game.getSelectedUnits()) {
        	text2 = text2 + unit.getReplayID() + ',';
        }
        text2 = text2.substring(0, text2.length() - 1);
        game.drawTextScreen(300,100, text2);
    }

    void run() {
        bwClient = new BWClient(this);
        bwClient.startGame();
    }
    
    public static void main(String[] args) {
        new Bot().run();
    }
}
```

When I parse reps using screp I get an in-game identifier which is "unitTag".

 I am looking for something similar through the JBWAPI, is there any unique identifier for the units (replayID or ID seem to work fine for the created units, but not for the 4 initial workers).

**Comment by JasperGeurtz** [comment]
Hi JuanPablo,

I can not reproduce your bug :(
Running your code (using jbwapi 1.4) on a live game and a replay gives me nonzero unique ID's

Live game (replayID 0 because not a replay):
![StarCraft_oOKcNGl7TR](https://user-images.githubusercontent.com/10107858/83174897-5a561000-a11b-11ea-9f19-61c003fec9dd.png)

Replay
![StarCraft_U12SJAYDSQ](https://user-images.githubusercontent.com/10107858/83174915-617d1e00-a11b-11ea-846a-500e82c40342.png)

**Comment by JasperGeurtz** [comment]
Ok nevermind, you are right something strange is going on, I'll investigate

**Comment by JuanPabloMF** [comment]
OK so it was a misunderstanding over the meaning of replayID from me. Since first values were all 0, but units created were not 0 I wasn't sure about it, but as you said it is an ID handled for replays (when I read the comments on getReplayID I got the idea that it was an in-game identifier).

ID works fine on the game for me.

**Comment by JasperGeurtz** [comment]
Yeah something is strange about replayID, they are all "0" on the first frame if you are **not** in a replay, so in an actual livegame. But afterwards, they are all nonzero.

Strange behavior, I pushed a small fix that at least after frame 1 it is "correct" (so even in live games, the units have replayID's).


I'd still suggest that you simply use "ID" as that seems to always work

**Comment by JuanPabloMF** [comment]
Great, thanks!
