### ISSUE TITLE
Unit.getInterceptors (and maybe getLarva) runs slowly

### ISSUE THREAD

**Issue by dgant** [JavaBWAPI/JBWAPI#68]
The implementation of `Unit.getInterceptors()` scales linearly with the number of units in the game, or roughly N^2 for a game with a lot of Carriers; this can be taxing late game because having a lot of Carriers means the total number of units is also likely quite high especially due to each Carrier holding 8 Interceptors.

For a sense of real-world scale: A recent PurpleWave game had `getInterceptors()` using about 1% of total CPU time, called once per frame for each Carrier. About half of that looked like evaluating the loop and half was allocating the collections which hold the interceptors.

https://github.com/JavaBWAPI/JBWAPI/blob/develop/src/main/java/bwapi/Unit.java#L1202

`Unit.getLarva()` works similarly and is likely subject to the same scaling: https://github.com/JavaBWAPI/JBWAPI/blob/develop/src/main/java/bwapi/Unit.java#L1228

**Comment by dgant** [comment]
The C++ BWAPI implementation of these methods avoids both the allocation and scan issues by re-using a UnitSet and then clearing + repopulating it each frame from the perspective of the interceptors via getCarrier()/getHatchery(): https://github.com/bwapi/bwapi/blob/3438abd8e0222f37934ba62b2130c3933b067678/bwapi/BWAPI/Source/BWAPI/GameUnits.cpp#L307 -- this limits the scale to O(n) and avoids new allocations.

**Comment by JasperGeurtz** [comment]
Good find, I will take a look and thanks for the reference implementation

**Comment by JasperGeurtz** [comment]
Suggested fix: e3e679549dad2f6dba8e10c00434fa1d27023a8a
